version: '3.1'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DBNERD_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DBNERD_ROOT_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/data/db